pipeline:

  init:
    image: quay.io/ukhomeofficedigital/dq-docker-terragrunt:5
    pull: true
    commands:
      - export AWS_DEFAULT_REGION=$${AWS_DEFAULT_REGION}
      - export AWS_ACCESS_KEY_ID=$${SANDPIT_AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=$${SANDPIT_AWS_SECRET_ACCESS_KEY}
      - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - ssh-keyscan -t rsa -p 2222 gitlab.digital.homeoffice.gov.uk >>  ~/.ssh/known_hosts
      - terragrunt init
    when:
      branch:
        exclude: [ master ]
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - NOTPROD_ACC_ID
      - NOTPROD_ACC_KEY
      - SSH_KEY

  
